#!/bin/bash

. VERSION
sed -e "s/HBASE_VERSION hbase-1.0.0/HBASE_VERSION hbase-${HBASE_VERSION}/g" Dockerfile > tmp.dockerfile
docker build -f tmp.dockerfile -t wangqiang8511/${IMAGE}-${HBASE_VERSION} .
docker tag -f wangqiang8511/${IMAGE}-${HBASE_VERSION}:latest wangqiang8511/${IMAGE}-${HBASE_VERSION}:$TAG
